### ISSUE TITLE
The redirect URI is not registered properly with DocuSign

### ISSUE THREAD

**Issue by rbmarques** [docusign/code-examples-java#10]
![image](https://user-images.githubusercontent.com/10132567/103367944-15290080-4aa5-11eb-93a0-798198ebe7e2.png)
After create and download a Quickstart App, I folloed the steps listed in installation guide and I recieve this error when try to run the application. I set my account datas and the message "The redirect URI is not registered properly with DocuSign" continue to apear.
Did I forget any settings?

![image](https://user-images.githubusercontent.com/10132567/103368267-e52e2d00-4aa5-11eb-9d51-f955e2febaa7.png)

**Comment by InbarGazit** [comment]
@rbmarques  can you copy/paste the URI that your browser is using when you get the error? it would have the encoded redirectURI, which you can add, but we can also add on our end to ensure this doesn't happen as well.

**Comment by rbmarques** [comment]
> @rbmarques can you copy/paste the URI that your browser is using when you get the error? it would have the encoded redirectURI, which you can add, but we can also add on our end to ensure this doesn't happen as well.

https://account-d.docusign.com/oauth/auth?prompt=login&client_id=0b5ad2f2-8cd5-408b-93e6-37ff1842faed&redirect_uri=http://localhost:8080/loginnull&response_type=code&scope=signature&state=46OzHx#/username

**Comment by InbarGazit** [comment]
you can try to add http://localhost:8080/loginnull to the list of URIs you have in there, and it would get rid of this error, but I'm wondering why this is happening. I'm looking into this.

**Comment by InbarGazit** [comment]
the correct URI should be http://localhost:8080/login?type=acg. This part is cut off, the URI is not encoded and you get a null coming from somewhere. Not sure yet how to reproduce this issue.

**Comment by rbmarques** [comment]
> http://localhost:8080/loginnull

When I added this URL, it's works.

Thank you so much!

![image](https://user-images.githubusercontent.com/10132567/103376457-71971a80-4abb-11eb-9afb-04b26c0440aa.png)

![image](https://user-images.githubusercontent.com/10132567/103376463-78259200-4abb-11eb-9161-6dbf3f9e11f1.png)

![image](https://user-images.githubusercontent.com/10132567/103376473-7eb40980-4abb-11eb-9539-5f68a91f57fa.png)

![image](https://user-images.githubusercontent.com/10132567/103376662-144f9900-4abc-11eb-9542-060ef510f61b.png)
