### ISSUE TITLE
request the authorization code without login

### ISSUE THREAD

**Issue by nujnay** [docusign/code-examples-java#12]
Is there any way users do not log in when https://account-d.docusign.com/oauth/auth; Or user do not visit https://account-d.docusign.com/oauth/auth; Or developer visit request the authorization code, user does not request the authorization code

**Comment by LarryKlugerDS** [comment]
Yes, use DocuSign's [JWT grant flow](https://developers.docusign.com/docs/esign-rest-api/sdk-tools/java/reference/).

It enables your app to impersonate an account user. The access token that you receive back can then be used to send envelopes, obtain a URL for an embedded signing ceremony, etc.

Signers do not need an account on DocuSign, only senders. If your application will enable someone to sign, then your app can get an access token for a "system user" such as "finance@example.com". Then impersonate the  finance@example.com user for sending the envelope and for obtaining the URL for the embedded signing ceremony.

Note that you need to impersonate an account user. The JWT for applications flow is not supported for the eSignature API.

If you have further questions of this nature, please ask on StackOverflow.com with tag `docusignapi`

**Comment by nujnay** [comment]
But how we can bypass this url https://account-d.docusign.com/oauth/auth?response_type=code&scope=signature%20impersonation&client_id=7&state=a39fh23hnf23&redirect_uri= Or not login by this url

**Comment by LarryKlugerDS** [comment]
That URL is for granting consent individually. It is a one time process. That URL is NOT processed by your application. The user who is being impersonated uses it one time from their browser (not from your application).

Or you can use administrative consent. 

This developer blog post may also be of help:
https://www.docusign.com/blog/developers/oauth-jwt-granting-consent 
We also have a video about Administrative Consent: https://www.youtube.com/watch?v=WAejcu-O1oE

**Comment by nujnay** [comment]
In any case, we need to let the user login first?

**Comment by LarryKlugerDS** [comment]
>we need to let the user login first?

No. The DocuSign user (the administrator/developer for the application), as a `one time process`, grants consent to your application to impersonate the sender of the envelope.

Later (forever), the application can obtain an access token that impersonates the DocuSign user. The user of your application does not need to login to sign documents.

**Comment by nujnay** [comment]
Thank you bro, love you
