### ISSUE TITLE
 production account api with invalid E-mail and / or password error

### ISSUE THREAD

**Issue by marlonfonsecadeoliveira** [docusign/code-examples-java#2]
setting in application.json,
production account 
authorization.code.grant.client.client-secret,
 but you are giving a password error or invalid email

**Comment by InbarGazit** [comment]
this example is set for the developer account/demo as it meant to help you learn and show you how to use the API. Most developers use demo/developer account. You cannot create integration key in production and so, I'm not sure how you can use this in production if you didn't go through the go-live process.

**Comment by SunStriderxxx** [comment]
NullPointer Error in method "EnvelopeSummary results = envelopesApi.createEnvelope(accountId, envelope)", i user java-client 3.6.0, but when i send envelop, i got an NullPointer Exception, i fount in 3.8.0 there is an try catch with
"updateAccessToken()" 
![image](https://user-images.githubusercontent.com/36763683/96867487-5b5b5580-149f-11eb-85d2-38fa54efbafb.png)
, which not found in 3.6.0,
![image](https://user-images.githubusercontent.com/36763683/96867504-61e9cd00-149f-11eb-99ef-4402a7b926be.png)

how can i solve it?

**Comment by LarryKlugerDS** [comment]
Closing.
