### ISSUE TITLE
Error No X11 DISPLAY variable not set

### ISSUE THREAD

**Issue by GBIEK** [docusign/code-examples-java#20]
Hello,
i get this error in github. Can i please help? Thanks you!

@GBIEK ➜ /workspaces/code-examples-java (master ✗) $  /usr/bin/env /opt/java/11.0.14/bin/java -agentlib:jdwp=transport=dt_socket,server=n,suspend=y,address=localhost:46125 @/tmp/cp_5qngrjy5gj0th2nhtjgsk18jn.argfile com.docusign.App 
14:19:17.952 [main] INFO com.docusign.App - Retrieving the default initialize context
Exception in thread "main" java.awt.HeadlessException: 
No X11 DISPLAY variable was set, but this program performed an operation which requires it.
        at java.desktop/java.awt.Desktop.getDesktop(Desktop.java:301)
        at com.docusign.App.main(App.java:48)
@GBIEK ➜ /workspaces/code-examples-java (master ✗) $

**Comment by DSDemo-LeandroReis** [comment]
Thank you for reaching out.
One of our engineers will come back to you shortly.

**Comment by InbarGazit** [comment]
Is this still an issue?
