### ISSUE TITLE
Screen is blank and no error shows up

### ISSUE THREAD

**Issue by rajashekhars-docsign** [docusign/code-examples-java#5]
I have downloaded the code with my developer account and ran it in both Eclipse and command line. Then logged in at Localhost:8080 with my developer account, then I see the error on the screen as ,
Oops, we have encountered a problem.

Message  and Dump are empty and no information is available. Tomcat don'
![docusign error](https://user-images.githubusercontent.com/73313108/96924856-41127f00-1481-11eb-87d3-861f22b81e73.png)
t have any error in console.

**Comment by AaronWDS** [comment]
Just to confirm, you're saying you used the Quickstart link generate and download the launcher from the site right?  Would you please confirm the Docusign SDK version in your pom.xml file in the project root?

**Comment by LarryKlugerDS** [comment]
Hi @rajashekhars-docsign  -- The best way to initially install this repo is to use the [QUICKSTART](https://developers.docusign.com/docs/esign-rest-api/quickstart/) app which will generate and configure an integration key for you.

You can generate and configure the integration key manually, but that is a lot more work and is more error-prone.

Please try again with the QuickStart app. Thanks, Larry

**Comment by rajashekhars-docsign** [comment]
Here is the version information,

<groupId>com.docusign</groupId>
<artifactId>code-examples-java</artifactId>
<version>1.0-SNAPSHOT</version>
<packaging>war</packaging>

<name>Docusign Java Tutorial</name>

<properties>
<java.version>11</java.version>
<oauth2.version>2.1.1.RELEASE</oauth2.version>
<commonsio.version>2.6</commonsio.version>
<docusign.version>3.8.0</docusign.version>
</properties>

Thanks and Regards,
Rajashekhar Sriramoju

**Comment by rajashekhars-docsign** [comment]
Yes, I logged in using my developer account and downloaded the Quick start
application and ran the application.

Thanks,
Rajashekhar Sriramoju

**Comment by rajashekhars-docsign** [comment]
I have downloaded the QuickStart app again today and I still see the same issue....

**Comment by LarryKlugerDS** [comment]
I'm sorry you're having this problem. Please email go-liveATATdocusignDOTDOTcom

**Comment by wnzltimprentice** [comment]
I had the same error. 

In Chrome i clicked F12 and found the following error in the console window: "login&type=acg:1 Failed to load resource: the server responded with a status of 401 ()"

I logged into DocuSign in incognito mode and hit the corporate firewall

I added added the Proxy Settings in the Spring Boot App class which fixed the issue:
System.setProperty("http.proxyHost", "...");
System.setProperty("http.proxyPort", "...");
System.setProperty("http.nonProxyHosts", "...");
System.setProperty("https.proxyHost", "...");
System.setProperty("https.proxyPort", "...");
System.setProperty("https.nonProxyHosts", "...");

I hope this is able to help others...

Oh I also found that trialing this test too many times will lock the DocuSign account. Another user will have to unlock you or Reset Password is required
