### ISSUE TITLE
Oops, we have encountered a problem.

### ISSUE THREAD

**Issue by MaliNetAI** [docusign/code-examples-java#6]
Please check your account configuration. If you are unable to resolve the problem, open a new issue on GitHub.

**Comment by AaronWDS** [comment]
Hello @MaliNetAI.  Please let us know, have you attempted to run the launcher through the Quickstart link or if you began from GitHub. Do you encounter the issue at login or when running an example?

**Comment by AaronWDS** [comment]
Following up with you, @MaliNetAI. Please let us know if your issue is still occurring.

**Comment by AaronWDS** [comment]
closing the thread, please open a new issue if you run into trouble, thanks!
