### ISSUE TITLE
Property not set

### ISSUE THREAD

**Issue by Michmich974** [docusign/code-examples-java#7]
When generate QuickStart app from "Apps and keys" admin page 
the key **jwt.grant.client.client-id** is set with **{JWT_API_ACCOUNT_ID}** instead of the integration key value.

Something like :
{
> ...
> jwt.grant.sso.redirect-url: "&type=jwt"
> jwt.grant.client.scope: "signature impersonation"
> jwt.grant.client.base-url: "account-d.docusign.com"
> **jwt.grant.client.client-id: "{JWT_API_ACCOUNT_ID}"**
> jwt.grant.client.private-key-path: "src/main/resources/private.key"
> ...
}

This occurs with the **Java** apps.
I don't know for the others languages

**Comment by AaronWDS** [comment]
Hi @Michmich974 We have recently [fixed this](https://github.com/docusign/code-examples-java/commit/465de49331d8d140499d27091496041262eb9454#diff-95e3817cc7391feb3a8e8a5d7e9c577941105d004049d6767558381f8c639b4dR25) mismatched variable in the Java Launcher.  Please try downloading the quickstart again and verify that your JWT Integration Key is there.
