### ISSUE TITLE
Example of "embedded signing" redirects to an external URL but shouldn't

### ISSUE THREAD

**Issue by hoto** [docusign/code-examples-java#8]
The official docusign documentation [here](https://developers.docusign.com/docs/esign-rest-api/how-to/request-signature-in-app-embedded/) says that embedded signing does NOT redirect the signer to an external url.

> ![image](https://user-images.githubusercontent.com/3105832/99313735-fbff2400-2857-11eb-91a5-e4ee61b8aeec.png)

The first example in this demo app description is called "Embedded Signing Ceremony":

> ![image](https://user-images.githubusercontent.com/3105832/99314254-b8f18080-2858-11eb-955e-86c2195d3e09.png)

AFAIC that demo does redirect the signer to an external URL but it shouldn't.  
Could someone point me to an example where the signer is NOT redirected to an external URL?
Or maybe I'm using this demo app incorrectly or I'm misreading something?

Embedded signing demo redirects to an external URL where the documentation suggest it wouldn't:

![justlikeoracle](https://user-images.githubusercontent.com/3105832/99314633-50ef6a00-2859-11eb-85b7-a2f19fd7494b.gif)

**Comment by InbarGazit** [comment]
hoto, the confusion is that you can do it in an iframe, without redirecting, or you can redirect. The two options are available to you. This shows how to redirect, but the iframe option is also available to you.

**Comment by LarryKlugerDS** [comment]
While an iFrame can be used for embedded signing it isn't recommended:

1. ID Verification feature doesn't work in an iFrame
1. Using an iFrame tempts the developer to add additional "chrome" above or adjacent to the signing ceremony. That does not work well when a mobile is used with the signing ceremony.
1. In the year 2020, there is no need to use an iFrame to maintain application state.
